paths:
  documents: /Users/klaushajdaraj/Windows Laptop Files/Thesis - All Files/Documents Folder - Thesis Empirical Results/
  data: /Users/klaushajdaraj/Projects/ml-treatment-effects/expdata.csv
  params: /Users/klaushajdaraj/Windows Laptop Files/Thesis - All Files/Documents Folder - Thesis Empirical Results/Params/
